### ISSUE TITLE
Install via pip does not yield templates/mongo.mako

### ISSUE THREAD

**Issue by gandy92** [JonnoFTW/pyramid_mongodb2#1]
**Observed behaviour:**
When I try to inspect a request in the debug toolbar, I get a page
```
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```
with an exception being logged as 
```
pyramid_mako.MakoRenderingException:

Traceback (most recent call last):
  File "c:\users\...\env-win7\lib\site-packages\pyramid_mako\__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "c:\users\...\env-win7\lib\site-packages\mako\template.py", line 482, in render_unicode
    self, self.callable_, args, data, as_unicode=True
  File "c:\users\...\env-win7\lib\site-packages\mako\runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "c:\users\...\env-win7\lib\site-packages\mako\runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "c:\users\...\env-win7\lib\site-packages\mako\runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "c:\users\...\env-win7\lib\site-packages\pyramid_debugtoolbar\templates\toolbar.dbtmako", line 56, in render_body
    ${history_tab()}
  File "c:\users\...\env-win7\lib\site-packages\pyramid_debugtoolbar\templates\history_tab.dbtmako", line 56, in render_history_tab
    ${panel.render_content(request)|n}
  File "c:\users\...\env-win7\lib\site-packages\pyramid_debugtoolbar\panels\__init__.py", line 102, in render_content
    return render(self.template, data, request=request)
  File "c:\users\...\env-win7\lib\site-packages\pyramid\renderers.py", line 75, in render
    result = helper.render(value, None, request=request)
  File "c:\users\...\env-win7\lib\site-packages\pyramid\renderers.py", line 470, in render
    result = renderer(value, system_values)
  File "c:\users\...\env-win7\lib\site-packages\pyramid_mako\__init__.py", line 144, in __call__
    template = self.template
  File "c:\users\...\env-win7\lib\site-packages\pyramid_mako\__init__.py", line 110, in template
    template = self.lookup.get_template(spec)
  File "c:\users\...\env-win7\lib\site-packages\pyramid_mako\__init__.py", line 75, in get_template
    "Can not locate template for uri %r" % uri)
TopLevelLookupException: Can not locate template for uri 'pyramid_mongodb2:templates/mongo.mako'
```

This is due to the fact, that the file templates/mongo.mako is missing from the distributed python package. 

**Possible solution:**
Maybe this can be resolved by adding a line to `MANIFEST.in`:
```
include pyramid_mongodb2/templates/*.mako
```

**Package versions:**
* pyramid==1.10.4
* pyramid-debugtoolbar==4.5
* pyramid-jinja2==2.8
* pyramid-mako==1.1.0
* pyramid-mongodb2==1.6.2
* pytest==5.2.1
* pytest-cov==2.8.1
* Mako==1.1.0
* waitress==1.3.1
* WebTest==2.0.33

**Comment by JonnoFTW** [comment]
Thanks for this. I'll make a fix.

**Comment by JonnoFTW** [comment]
@gandy92 this should be fixed in 3508314a003a005c16f961c05e2ebcb217cb5b76 and I've updated pypi, please try again and let me know how you go.

**Comment by gandy92** [comment]
Thanks for reacting so promptly. Unfortunately, after the upgrade, I only get a `pyramid_mongodb2-1.6.4.dist-info/` without the previously present `pyramid_mongodb2/`. 

Strangely, the RECORD file in the wheel does not contain any files from the .tar.gz:
```
pyramid_mongodb2-1.6.4.dist-info/METADATA,sha256=sklWXNbUCISXcW980HoWOamBK95Bl02o2gMWeiRns44,4743
pyramid_mongodb2-1.6.4.dist-info/WHEEL,sha256=v8slff5hmCpvciQ3G55d2d1CnOBupjDFJHDE2dUb1Ao,97
pyramid_mongodb2-1.6.4.dist-info/top_level.txt,sha256=AbpHGcgLb-kRsJGnwFEktk7uzpZOCcBY74-YBdrKVGs,1
pyramid_mongodb2-1.6.4.dist-info/RECORD,,
```

I cloned the repository and tried to find a fix, but I seem to lack the setuptools expertise...

**Comment by gandy92** [comment]
Found it: Apparently, wheel does not honor the `MANIFEST.in` (see https://stackoverflow.com/questions/24347450/how-do-you-add-additional-files-to-a-wheel)

With an additional 
```
package_data = {
    'pyramid_mongodb2': ['templates/*.mako']
}
```
and `package_data=package_data` to `setup()` in `setup.py`, a `python3 setup.py bdist_wheel` appears to yield a correct wheel file.

**Comment by ChrisBarker-NOAA** [comment]
yeah, there are multiple ways to include "extra" files in a package. I *think* the deal is that "manifest.in" is for including files in the distribution tarball, whereas "package_data" is for including non-python files in the installed package itself. So the right thing to do here.

On the other note, I found that installing from the PyPi tarball (version 1.6.4) yielded:

"pyramid_mongodb2-1.6.4.dist-info/ without the previously present pyramid_mongodb2/" as @gandy92 indicated.

And I don't think the manifest,in or package_data has anything to do with that.

Maybe I'll debug it in a bit.

**Comment by ChrisBarker-NOAA** [comment]
OK -- figure it out, and cleaned it up in PR #3 

It would be great to get a new release out.

**Comment by JonnoFTW** [comment]
@ChrisBarker-NOAA do I need to run setup.py differently to build things now?

EDIT: I've updated it on pypi, please install it from there and let me know if it works for you.

**Comment by ChrisBarker-NOAA** [comment]
Nope: it will just work now :-)

-CHB

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115 <x-apple-data-detectors://6/1>       (206) 526-6317
main reception

On Dec 28, 2019, at 5:57 AM, Jonathan Mackenzie <notifications@github.com>
wrote:

﻿

@ChrisBarker-NOAA <https://github.com/ChrisBarker-NOAA> do I need to run
setup.py differently to build things now?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JonnoFTW/pyramid_mongodb2/issues/1?email_source=notifications&email_token=AAG7YYDR4G3ESAOQ36DDQCLQ25LM3A5CNFSM4I6OD2X2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHYKOHI#issuecomment-569419549>,
or unsubscribe

**Comment by ChrisBarker-NOAA** [comment]
Thanks! I’ll try it put later. 

FYI, I’m planning  in on putting it on conda-forge:

https://conda-forge.org/

Would you like to be a maintainer?

**Comment by ChrisBarker-NOAA** [comment]
I've tested thelatest PyPi build, and it appears to be working -- thanks!

I've submitted a recipe to conda-forge, if you are interested:

https://github.com/conda-forge/staged-recipes/pull/10503

NOTE: it would be a good idea to create a "release" here on gitHub as well, when you post a version to PyPi.
